# Generated by Django 5.2.15 on 2026-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('parent_name', models.CharField(blank=True, max_length=120, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('referring_dentist', models.CharField(blank=True, max_length=120, null=True)),
                ('dentist_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('reason_for_referral', models.CharField(blank=True, choices=[('Consult', 'Consult'), ('Root Canal Treatment', 'Root Canal Treatment'), ('Retreatment', 'Retreatment')], max_length=50, null=True)),
                ('tooth_numbers', models.CharField(max_length=120)),
                ('comments', models.TextField(blank=True, null=True)),
                ('insurance_name', models.CharField(max_length=120)),
                ('insurance_id', models.CharField(max_length=120)),
                ('policy_holder', models.CharField(blank=True, max_length=120, null=True)),
                ('group_number', models.CharField(blank=True, max_length=120, null=True)),
                ('radiograph_1', models.FileField(blank=True, null=True, upload_to='radiographs/')),
                ('radiograph_2', models.FileField(blank=True, null=True, upload_to='radiographs/')),
                ('radiograph_3', models.FileField(blank=True, null=True, upload_to='radiographs/')),
                ('radiograph_4', models.FileField(blank=True, null=True, upload_to='radiographs/')),
                ('radiograph_5', models.FileField(blank=True, null=True, upload_to='radiographs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'referral entry',
                'verbose_name_plural': 'referral entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
